name: hspec-pretty-json

copyright: (c) 2022-2023 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
  - base >= 4.11.0.0 && < 5
  - aeson
  - aeson-pretty == 0.8.*
  - hspec-core >= 2.10 && < 3
  - text
  - bytestring

source-dirs: src

library: {}

tests:
  spec:
    cpp-options: -DTEST
    ghc-options: -pgmL markdown-unlit
    build-tools:
      - hspec-discover
      - markdown-unlit
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
