name: hspec-pretty-json

copyright: (c) 2022 Simon Hengel
author: Simon Hengel <sol@typeful.net>

ghc-options: -Wall

dependencies:
  - base == 4.*
  - aeson
  - aeson-pretty
  - hspec-core
  - text
  - bytestring

source-dirs: src

library: {}

tests:
  spec:
    cpp-options: -DTEST
    build-tools: hspec-discover
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
